name: f_biuli
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: 3.38.3

dependencies:
  flutter:
    sdk: flutter

  analyzer: '>=7.7.1 <10.0.0'
  build: '>=3.1.0 <5.0.0'
  cupertino_icons: ^1.0.2
  dio: ^5.9.0
  freezed_annotation: ^3.0.0
  get_it: ^8.2.0
  go_router: ^16.2.1
  html: ^0.15.4
  json_annotation: ^4.9.0
  logger: ^2.6.0
  logging: ^1.3.0
  provider: ^6.1.5
  retrofit: ^4.9.1
  #rxdart: ^0.28.0
  sentry_flutter: ^9.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  
  # https://github.com/flutter/flutter/issues/175071
  build_runner: ^2.6.0
  
  freezed: ^3.0.6
  go_router_builder: ^4.1.0
  json_serializable: ^6.10.0
  retrofit_generator: ^10.2.0

flutter:
  uses-material-design: true

